require "user.options"
require "user.plugins"
require "user.colors"
require "user.airline"
require "user.keymaps"
require("somethign")
require "user.autocommands"
require "user.nvimtree"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.outline"
require "user.blameline"
require "user.gitsigns"
