require "user.plugins"

require "user.go"
require "user.airline"
require "user.autocommands"
require "user.cmp"
require "user.colors"
require "user.dap"
require "user.dapgo"
require "user.dapui"
require "user.keymaps"
require "user.loghighlight"
require "user.lsp"
require "user.nvimtree"
require "user.options"
require "user.outline"
require "user.telescope"
require "user.treesitter"
require "user.gitblame"
require "user.gitsigns"
require "user.rest"
require "user.vennvim"

require "user.comment"
require "user.copilot"

-- require "user.conform"
