#!/bin/zsh

# Colorize grep output (good for log files)
if ! command -v rg &> /dev/null;
then
	alias grep='grep --color=auto'
else
    alias rg="rg --hidden"
	alias grep="rg"
fi
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias bat='batcat'
alias l='ls -lah --group-directories-first --color=auto'

# have xclip always copy to the system clipboard
alias xclip="xclip -selection clipboard"

# For reattaching work monitor
alias work-display="xrandr --output eDP-1 --mode 1920x1080 --pos 0x1080 --rotate normal --output DP-1 --off --output HDMI-1 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output DP-2 --off"

# For reattaching home monitor
alias home-display="xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-2 --off"

# Kubectl aliases
alias kc='kubectl '
alias kns='kubectl config set-context --current --namespace '
alias kctx='kubectl config use-context '
