#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=2000000

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/bin":$PATH
export ZSH="$ZDOTDIR/.oh-my-zsh"
export EDITOR="nvim"
export BROWSER="chromium"
export BAT_THEME="zenburn"
export TERMINAL="kitty"
export PAGER="less"
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export GOPATH="$HOME/go"
export GOBIN="/usr/local/go/bin"
export PATH=$PATH:$GOBIN
export PATH=$PATH:$GOPATH/bin
export PATH="$HOME/.local/bin/lua-language-server/bin":$PATH
export REVIEW_BASE=master


export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
export MANPAGER='less -s -M +Gg'
