#!/bin/bash
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=2000000

export EDITOR="nvim"
export BROWSER="chromium"
export BAT_THEME="zenburn"
export TERMINAL="kitty"
export PAGER="less"
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export GOBIN="$HOME/go/bin"
export REVIEW_BASE=master
export GLASSFISH_HOME=/opt/glassfish7

export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal
export MANPAGER='less -s -M +Gg'


# Update path
# Array of directories to check
DIRS_TO_CHECK=(
    $GOBIN
    $GLASSFISH_HOME/bin
    "/usr/local/go/bin"
)

# Loop over each directory in the array
for DIR in "${DIRS_TO_CHECK[@]}"; do
  # Check if the directory is in the PATH
  if [[ ":$PATH:" != *":$DIR:"* ]]; then
    # If not, add the directory to the PATH
    export PATH="$PATH:$DIR"
  fi
done
